# Generated by Django 4.0.1 on 2022-02-17 11:46

from django.db import migrations
from ..models import HealthCheck

def create_counter(*args, **kwargs):
    instance, created = HealthCheck.objects.get_or_create()
    message = "created" if created else "recieved"
    print(f"Counter {instance} was {message}")


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_healthcheck'),
    ]

    operations = [
        migrations.RunPython(create_counter)
    ]
